### ISSUE TITLE
Group Projects by Domain Area

### ISSUE THREAD

**Issue by WardLT** [globus-labs/globus-labs.github.io#49]
We have too many projects to sift through quickly. Perhaps group them by different areas or attach tags to them.

**Comment by WardLT** [comment]
Add links from projects to people as well

**Comment by gpauloski** [comment]
Domains Areas:
- Machine Learning (Colmena, KAISA)
- Edge Computing (FuncX, )
- Materials Science (Colmena, )
- Climate Science (Clouds, )
- Data Accessibility (Xtract, DLHub, Foundry, Globus Search, Materials Data Facility, )
- Compute Frameworks (Colmena, FuncX, Parsl, )

Uncategorizes: AI4PFAS, Cost-Aware, CODAR, Flows, Gladier, SZ3 Compression, Whole Tale

**Comment by gpauloski** [comment]
Project update assignments (I'll post these on slack):
- AI4PFAS: Ganesh
- Clouds: Tak
- Colmena: Logan
- XTract: remove
- dlhub/garden: KJ/Ari/Ben
- Flows: Jim and Ryan
- Foundry: KJ/Ari/Ben
- Funcx: kyle/ryan
- parsl: kyle
- Gladier: raf
- Globus search: remove
- info extraction: hong/aswathy
- KFAC: greg
- MDF: ben and co
- compressionL yuanjian
- whole tale: kyle
- proxystore: greg/valerie
- SDL: raf
- flox: matt and Nathaniel

**Comment by WardLT** [comment]
Some guidance to include in the template:

1. Use active voice ("we")
1. Have the introductory paragraph be 3 sentences or less
1. Keep the overall length to under 3 paragraphs
1. Include bullet lists if possible
1. Include links to any other project pages/github repos

An example first paragraph:

- _Sentence giving overall context, hinting at the problem we solve._ "Most humans don't like to read long paragraphs and writing short ones takes thought."
- _An explanation of how we fix it._ "We made a simple template that you can follow for how to write one."
- _A statement of impact_. "Any Globus Labs member need only edit this template to make their science more accessible."

**Comment by gpauloski** [comment]
Mostly closed by #70. Now up to others to use the tags.
